#server:
#  port: 8099    #default port where the service will be started

eureka:         #tells about the Eureka server details and its refresh time
  registerwithEureka: true
  fetchregistry: true
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://172.23.239.168:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: muzicapp
    #current service name to be used by the eureka server

management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.

#logging:
#  level:
#    com.example.howtodoinjava: DEBUG